version: '2'
services:
    materialandstockmanagement-app:
        image: materialandstockmanagement
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://materialandstockmanagement-postgresql:5432/MaterialAndStockManagement
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=materialandstockmanagement-elasticsearch:9300
        ports:
            - 8080:8080
    materialandstockmanagement-postgresql:
        extends:
            file: postgresql.yml
            service: materialandstockmanagement-postgresql
    materialandstockmanagement-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: materialandstockmanagement-elasticsearch
